-- MySQL Script generated by MySQL Workbench
-- Fri 15 Jun 2018 03:11:38 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spiros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spiros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spiros` DEFAULT CHARACTER SET utf8 ;
USE `spiros` ;

-- -----------------------------------------------------
-- Table `spiros`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spiros`.`user` ;

CREATE TABLE IF NOT EXISTS `spiros`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `firstname` VARCHAR(300) NULL,
  `lastname` VARCHAR(300) NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `spiros`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spiros`.`customer` ;

CREATE TABLE IF NOT EXISTS `spiros`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(320) NULL DEFAULT NULL,
  `phone_number` VARCHAR(50) NULL DEFAULT NULL,
  `firstname` VARCHAR(300) NULL DEFAULT NULL,
  `lastname` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spiros`.`estimate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spiros`.`estimate` ;

CREATE TABLE IF NOT EXISTS `spiros`.`estimate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
